language: node_js
node_js:
  - '8'
  - '10'
install:
  - npm install -g codecov
script:
  - npm run build
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
sudo: false
