version: 2.1
orbs:
  node: circleci/node@2.0.2
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/node:10.0-browsers
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: yarn
      - run: yarn build
      - run: 'export DISPLAY=:0.0'
      - run: yarn test
      - run: echo | ls
      - run: echo | ls coverage
      - codecov/upload:
        file: 'coverage/coverage-final.json'      