version: 2.1
orbs:
  node: circleci/node@2.0.2
  codecov: codecov/codecov@1.0.5
jobs:
  install-node-example:
    docker:
      - image: selenium/standalone-chrome:3.1.0 
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y curl
      - node/install:
          install-yarn: true
          node-version: latest
      - run: node --version
      - run: yarn --version
      - run: yarn
      - run: yarn build
      - run: yarn coverage
      - codecov/upload:
        file: 'coverage/report-lcov/lcov.info'
      
workflows:
  build-and-test:
    jobs:
      - install-node-example