version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  install:
    steps:
      - checkout
      - run: npm install
  build:
    steps:
      - run: npm run build
  test:
    steps:
      - run: npm run coverage
workflows:
  build-and-test:
    jobs:
      - install
      - build
      - test
