version: 2.1
orbs:
  node: circleci/node@2.0.2
jobs:
  install-node-example:
    docker:
      - image: selenium/standalone-chrome:3.1.0 
    steps:
      - checkout
      - sudo apt-get upgrade
      - sudo apt-get install curl
      - node/install:
          install-yarn: true
          node-version: latest
      - run: node --version
      - run: yarn --version
workflows:
  build-and-test:
    jobs:
      - install-node-example